name: null
project: Lux_AI_2021
entity: isaiahpressman
group: after_september_patch
act_space: BasicActionSpace
obs_space: FixedShapeContinuousObsV2
obs_space_kwargs: {}
reward_space: GameResultReward
reward_space_kwargs: {}
total_steps: 60000000.0
num_actors: 2
n_actor_envs: 16
unroll_length: 16
batch_size: 4
discounting: 0.999
model_arch: conv_model
n_blocks: 24
hidden_dim: 128
embedding_dim: 32
n_merge_layers: 1
normalize: false
sum_player_embeddings: false
use_index_select: false
rescale_value_input: true
rescale_se_input: true
kernel_size: 5
optimizer_class: Adam
optimizer_kwargs:
  lr: 1.0e-05
  eps: 0.0003
min_lr_mod: 1.0
entropy_cost: 2.0e-05
baseline_cost: 1.0
teacher_kl_cost: 0.001
teacher_baseline_cost: 0.0
lmb: 0.9
reduction: sum
use_teacher: true
teacher_load_dir: /Windows/Users/isaia/Documents/GitHub/Kaggle/Lux_AI_2021/outputs/11-01/00-18-25/
teacher_checkpoint_file: 30555200.pt
actor_device: cuda:1
learner_device: cuda:0
disable_wandb: false
model_log_freq: 100
sharing_strategy: file_descriptor
load_dir: /Windows/Users/isaia/Documents/GitHub/Kaggle/Lux_AI_2021/outputs/11-08/19-19-08/
checkpoint_file: 56334848.pt
weights_only: false
n_value_warmup_batches: 0
seed: null
num_buffers: 4
use_mixed_precision: true
clip_grads: 10.0
checkpoint_freq: 10.0
num_learner_threads: 1
debug: false
